- name: Check update
  hosts: all
  tasks:
    - name: Callback valid playbook for 5.1
      shell: touch /tmp/test5-1
      when: ansible_local.version.os_ver == "5" and ansible_local.version.os_subver == "1"
    
    - name: Callback valid playbook for 5.2
      uri:
        url: https://10.17.11.11:443/api/v2/job_templates/18/callback/
        method: POST
        body: host_config_key=bce91c33-bf03-4033-9f64-ac162f6babb8
        body_format: form-urlencoded
        validate_certs: no
      when: ansible_local.version.os_ver == "5" and ansible_local.version.os_subver == "2"
      
    - name: Callback valid playbook 5.3
      shell: touch /tmp/test5-3
      when: ansible_local.version.os_ver == "5" and ansible_local.version.os_subver == "3"
    
