- name: Add MAC address on DHCP pool
  hosts: "{{cisco_firewall}}-fw"
  gather_facts: no
  tasks:    
    - name: Execute hardware-address
      cisco.ios.ios_config:
        lines:
        - hardware-address {{ mac }}
        parents: ip dhcp pool DHCP_{{ terminal_pool }}
        match: exact
