- name: Cahnge MAC address on DHCP pool
  hosts: all
  gather_facts: no
  tasks:
    - name: Delete MAC address
      cisco.ios.ios_command:
        commands: 
        - conf t
        - ip dhcp pool {{terminal_pool}}
        - no hardware-address
        - hardware-address {{hardware_address}}
