- name: Add MAC address on DHCP pool
  hosts: "{{cisco_firewall}}-fw"
  gather_facts: no
  tasks: 
    - name: Get IP pool config
      cisco.ios.ios_command:
        commands:
        - show arp | inc {{ terminal_ip }}
      register: output

    - name: Extract new MAC
      set_fact:
        mac: "{{ output.stdout | regex_replace('^.*([a-z0-9]{4}.[a-z0-9]{4}.[a-z0-9]{4}).*$', '\\1') }}"
        
    - name: Print output
      debug:
        msg: "Nowy MAC adres: {{ mac }}"
        
    - name: Execute hardware-address
      cisco.ios.ios_config:
        lines:
        - hardware-address {{ mac }}
        parents: ip dhcp pool DHCP_{{ terminal_pool }}
        match: exact
