
- name: Show Cisco FW Interfaces status
  hosts: "{{cisco_firewall}}-fw"
  gather_facts: no
    cisco.ios.ios_command:
      commands: show interfaces status
    register: output

    debug:
      msg: "{{ output.stdout[0].split('\n') }}"
