- name: Backup Cisco Firewall Config to remote destination
  hosts: all
  tasks:
    - name: print running config
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: /tmp/          
