- name: Add MAC address on DHCP pool
  hosts: "{{cisco_firewall}}-fw"
  gather_facts: no
  tasks: 
    - name: Get IP pool config
      cisco.ios.ios_command:
        commands:
        - show arp | inc {{ terminal_ip }}
      register: output

    - name: Extract new MAC
      set_fact:
        mac: "{{ output | regex_replace('^.*([a-z0-9]{4}.[a-z0-9]{4}.[a-z0-9]{4}).*$', '\\1') }}"
        
    - name: Print output
      debug:
        msg: "Nowy MAC adres: {{ mac }}"
