- name: identify reachable hosts
  hosts: all
  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to {{inventory_hostname}}"

- name: Backup Cisco Firewall Config to remote destination
  hosts: running_hosts
  ignore_unreachable: yes
  max_fail_percentage: 70
  gather_facts: no
  tasks:
    - name: Print running config
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: /tmp/
      register: config_output
    
    - name: Remove non config lines
      lineinfile:
        path: "{{config_output.backup_path}}"
        line: "Building configuration..."
        state: absent

    - name: Remove non config lines - REGEXP
      lineinfile:
        path: "{{config_output.backup_path}}"
        regexp: 'Current configuration.*'
        state: absent

    - name: Create dir
      local_action: command ssh 10.17.11.10 "if [ ! -d /tmp/{{config_output.date}}/{{inventory_hostname}} ]; then mkdir -p /tmp/{{config_output.date}}/{{inventory_hostname}}; fi"
              
    - name: Move file to remote dir
      local_action: command scp {{config_output.backup_path}} 10.17.11.10:/tmp/{{config_output.date}}/{{inventory_hostname}}
    
    - name: Remove local file
      file: 
        path: "{{config_output.backup_path}}"
        state: absent
