- name: Delete MAC address on DHCP pool
  hosts: "{{cisco_firewall}}-fw"
  gather_facts: no
  tasks:
    - name: Execute no hardware-address
      cisco.ios.ios_config:
        lines:
        - no hardware-address
        parents: ip dhcp pool DHCP_{{terminal_pool}}
        match: exact
    - name: Get IP pool config
      cisco.ios.ios_command:
        commands:
        - show ip dhcp pool DHCP_{{terminal_pool}}
      register: output
   
    - name: Extract IP address
      set_fact:
        pool_ip: "{{ output.stdout[-1] | replace('\n', '') | regex_replace('([0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})', '\\1') }}"
   
    - name: Print output
      debug:
        msg: "{{ pool_ip }}"
