- name: Cahnge MAC address on DHCP pool
  hosts: all
  tasks:
    - name: Delete MAC address
      cisco.ios.ios_command:
        commands: 
        - conf t
        - ip dhcp pool DHCP_TZONE_T1
        - no hardware-address
