- name: Delete MAC address on DHCP pool
  hosts: "{{cisco_firewall}}-fw"
  gather_facts: no
  cisco.ios.ios_config:
    lines:
    - no hardware-address
    parents: ip dhcp pool DHCP_{{terminal_pool}}
    match: exact
