- name: Delete MAC address on DHCP pool
  hosts: "{{cisco_firewall}}-fw"
  gather_facts: no
  tasks:
    - name: Execute no hardware-address
      cisco.ios.ios_config:
        lines:
        - no hardware-address
        parents: ip dhcp pool DHCP_{{terminal_pool}}
        match: exact
    - name: Get IP address
      cisco.ios.ios_command:
        commands:
        - show ip dhcp pool DHCP_{{terminal_pool}}
      register: output
    - name: Print output
      debug:
        msg: {{output}}
        var: output
