- name: Download update file
  hosts: all
  tasks:
    - name: Download cups config
      get_url:
        url: http://repo/repo/cups.tar.gz
        dest: /tmp/cups.tar.gz
        checksum: sha256:09fd784cc4814faa7569548e88d199a8a71d8ddcb05c2f23ee1e82bd975c46cd
        mode: '0660'
        
    - name: Download firefox start script
      get_url:
        url: http://repo/repo/firefox-start.sh
        dest: /tmp/firefox-start.sh
        checksum: sha256:756cc3031d487c375d6f01524b52655e950ca8e5d1a50d2faf6890fa076bea45
        mode: '0777'
