- name: Check if SNMPv2 is working on remote host
  hosts: "{{ branch_no }}-printer{{printer_no}}"
  connection: local
  gather_facts: no
 
  tasks:
    - name: Get SNMPv2 printer model
      local_action: command snmpget -v2c -c public {{ inventory_hostname }} SNMPv2-MIB::sysDescr.0
      register: response

    - name: Set printer model fact
      set_fact:
        printer_model: "{{ response.stdout | regex_replace('.*STRING: (.*); .*', '\\1') | regex_replace('.*STRING: (.*)', '\\1')}}"

    - name: Configure printer Xerox
      
      block:
        - name: Print model
          debug:
            msg: "To jest drukarka Xerox"
         
        - name: get email address
          uri:
            url: "http://{{inventory_hostname}}/addressbook/GetIndividualInABook.cgi"
            method: POST
            return_content: yes
            body_format: form-urlencoded
            body:
              ispeedNo: 0
              start: 0
              limit: 1000
            headers:
              Cookie: SESSION_ID=3554
              statusSelected: 1
          
        - name: set email address
          uri:
            url: "http://{{inventory_hostname}}/addressbook/SetIndividualInABook.cgi"
            method: POST
            return_content: yes
            force_basic_auth: yes
            url_username: "admin"
            url_password: "1111"
            body_format: form-urlencoded
            body:
              DISPLAYNAME: "{{email}}"
              EMAIL: "{{email}}"
              CMD: add
            headers:
              Cookie: SESSION_ID=3554
          register: output_set_email
          when: email | default('', true) | trim != ''
        
        - name: Parse output
          set_fact:
            output_set_email_fact: "{{ output_set_email.content | replace(':', ': ') | from_yaml }}"
        
        - name: Pokaz output
          debug:
            msg: "{{ output_set_email_fact.success }}"
          
      when: printer_model == 'Xerox WorkCentre 3345'

    - name: Configure printer Samsung
      block:
        - name: Print model
          debug:
            msg: "To jest drukarka Samsung"
            
        - name: Pokaz rozdzielczość
          debug:
            msg: "Rozdzieloczość ustawiona na {{scan_resolution}}"
          when: scan_resolution is defined
        
        - name: Pokaz rozdzielczość
          debug:
            msg: "Email ustawiona na {{email}}"
          when: email is defined                
          
      when: printer_model == 'Samsung SL-M3870FW'      
