- name: Check if SNMPv2 is working on remote host
  hosts: "{{ branch_no }}-printer{{printer_no}}"
  connection: local
  gather_facts: no
 
  tasks:
    - name: Get SNMPv2 printer model
      local_action: command snmpget -v2c -c public {{ inventory_hostname }} SNMPv2-MIB::sysDescr.0
      register: response

    - name: Set printer model fact
      set_fact:
        printer_model: "{{ response.stdout | regex_replace('.*STRING: (.*); .*', '\\1') | regex_replace('.*STRING: (.*)', '\\1')}}"

    - name: Configure printer Xerox
      
      block:
        - name: Print model
          debug:
            msg: "To jest drukarka Xerox"
         
        - name: get email address
          uri:
            url: "http://{{inventory_hostname}}/addressbook/GetIndividualInABook.cgi"
            method: POST
            return_content: yes
            body_format: form-urlencoded
            body:
              ispeedNo: 0
              start: 0
              limit: 1000
            headers:
              Cookie: SESSION_ID=3554
              statusSelected: 1
   
        - name: set email server
          uri:
            url: "http://{{inventory_hostname}}/properties/services/email/SetSmtpCfg.cgi"
            method: POST
            return_content: yes
            body_format: form-urlencoded
            body:
              GSI_SMTP_DOMAIN: SSG5-v92
              GSI_SMTP_SERVER_TYPE: 1
              serverType: 1
              GSI_SMTP_SERVER_IP_ADDR: 192.168.95.10
              GSI_SMTP_PORT_NUMBER: 25
              GSI_MACHINE_EMAIL_ADDR: agent@printersmtp.partner-alior.pl
              GSI_SMTP_ENAUTH: OFF
              saveNewSmtpPassword: OFF
              GSI_SMTP_SSL_ENABLE: 0
              GSI_VALIDATE_SERVER_CERTIFICATE: OFF
              GSI_SMTP_MAX_SIZE: 32
            headers:
              Cookie: SESSION_ID=3554
              Authorization: "Basic YWRtaW46MTExMQ=="

          
        - name: set email address
          uri:
            url: "http://{{inventory_hostname}}/addressbook/SetIndividualInABook.cgi"
            method: POST
            return_content: yes
            body_format: form-urlencoded
            body:
              DISPLAYNAME: "{{email}}"
              EMAIL: "{{email}}"
              CMD: add
            headers:
              Cookie: SESSION_ID=3554
              Authorization: "Basic YWRtaW46MTExMQ=="
          register: output
          when: email | default('', true) | trim != ''
          
        - name: Pokaz output
          debug:
            msg: "{{output.content.succes}}"
          
      when: printer_model == 'Xerox WorkCentre 3345'

    - name: Configure printer Samsung
      block:
        - name: Print model
          debug:
            msg: "To jest drukarka Samsung"
            
        - name: Pokaz rozdzielczość
          debug:
            msg: "Rozdzieloczość ustawiona na {{scan_resolution}}"
          when: scan_resolution is defined
        
        - name: Pokaz rozdzielczość
          debug:
            msg: "Email ustawiona na {{email}}"
          when: email is defined                
          
      when: printer_model == 'Samsung SL-M3870FW'      
