- name: Check if SNMPv2 is working on remote host
  hosts: "{{ branch_no }}-printer{{printer_no}}"
  connection: local
  gather_facts: no
 
  tasks:
    - name: Test SNMPv2
      local_action: command snmpget -v2c -c public {{ inventory_hostname }} SNMPv2-MIB::sysDescr.0
      register: response
      ignore_errors: True
 
    - name: Print the complete response
      debug:
        msg: "{{ response.stdout }}"
