- name: Printer configuration
  hosts: "{{ branch_no }}-printer{{printer_no}}"
  connection: local
  gather_facts: no
 
  tasks:
    - name: Discover printer model
      local_action: command snmpget -v2c -c public {{ inventory_hostname }} SNMPv2-MIB::sysDescr.0
      register: response

    - name: Set printer model fact
      set_fact:
        printer_model: "{{ response.stdout | regex_replace('.*STRING: (.*); .*', '\\1') | regex_replace('.*STRING: (.*)', '\\1')}}"

    - name: Configure Xerox printer
      
      block:
        - name: Print model
          debug:
            msg: "Rozpoznałem drukarke WorkCentre 3345"
          
        - name: Add email address
          block:
            - name: Run URL command 
              uri:
                url: "http://{{inventory_hostname}}/addressbook/SetIndividualInABook.cgi"
                method: POST
                return_content: yes
                force_basic_auth: yes
                url_username: "{{ xerox_user }}"
                url_password: "{{ xerox_password }}"
                body_format: form-urlencoded
                body:
                  DISPLAYNAME: "{{email}}"
                  EMAIL: "{{email}}"
                  CMD: add
                headers:
                  Cookie: SESSION_ID=3554
              register: output_set_email
        
            - name: Parse output
              set_fact:
                output_set_email_fact: "{{ output_set_email.content | replace(':', ': ') | from_yaml }}"
        
            - name: Print result
              debug:
                msg: "Ustawiono adres email {{ email }}"
              when: output_set_email_fact.success
              
            - name: Print result
              debug:
                msg: "Nie ustawiono adresu email!!!"
              when: not output_set_email_fact.success
              
          when: email | default('', true) | trim != ''
          
        - name: Change paper tray
          block:
            - name: Run URL command - copy tray
              uri:
                url: "http://{{inventory_hostname}}/properties/services/copy/SetCopyConfiguration.cgi"
                method: POST
                return_content: yes
                force_basic_auth: yes
                url_username: "{{ xerox_user }}"
                url_password: "{{ xerox_password }}"
                body_format: form-urlencoded
                body:
                  COPY_PAPER_SOURCE_OP: "{{tray}}"
                headers:
                  Cookie: SESSION_ID=3554
              register: output_set_copy_tray
        
            - name: Print result
              debug:
                msg: "Ustawiono tace kopiowania: {{ tray }}"
              when: not output_set_copy_tray.failed
              
            - name: Print result
              debug:
                msg: "Nie ustawiono tacy kopiowania!!!"
              when: output_set_copy_tray.failed

            - name: Run URL command - print tray
              uri:
                url: "http://{{inventory_hostname}}/SaveChanges.cgi"
                method: POST
                return_content: yes
                force_basic_auth: yes
                url_username: "{{ xerox_user }}"
                url_password: "{{ xerox_password }}"
                body_format: form-urlencoded
                body:
                  GSI_AUTO_TRAY_SWITCH:	"0"
                  GSI_PCL_IGNORE_PAPER_SIZE:	"1"
                headers:
                  Cookie: SESSION_ID=3554
              register: output_set_print_tray
           
            - name: Print result
              debug:
                msg: "Ustawiono tace drukowania: Bypass=off, Tray Switching=disabled"
              when: not output_set_print_tray.failed
              
            - name: Print result
              debug:
                msg: "Nie ustawiono tacy kopiowania!!!"
              when: output_set_print_tray.failed 
         
          when: tray | default('', true) | trim != ''

        - name: Delete jobs
          block:
            - name: Run URL command - get jobs id
              uri:
                url: "http://{{inventory_hostname}}/jobs/activeJobs.dhtml"
                method: POST
                return_content: yes
                force_basic_auth: yes
                url_username: "{{ xerox_user }}"
                url_password: "{{ xerox_password }}"
                headers:
                  Cookie: SESSION_ID=3554
                  JOB_SUBMISSION: ""
              register: output_del_jobs
              
            - name: Set fact jobs id
              set_fact:
                jobs_id_fact: "{{output_del_jobs.content | replace('\t','') | replace('\r','') | replace('\n','') | regex_replace('.*varjobIndex.*\"(.*)\".*varjobName=.*', '\\1') }}"
            
            - name: Usuwam zadania!
              uri:
                url: "http://{{inventory_hostname}}/jobs/DeleteActiveJob.cgi"
                method: POST
                return_content: yes
                force_basic_auth: yes
                url_username: "{{ xerox_user }}"
                url_password: "{{ xerox_password }}"
                body_format: form-urlencoded
                body:
                  delIndex:	"{{ item }}"
                  selIndex: "0"
                  secureId: ""
                headers:
                  Cookie: SESSION_ID=3554
                  JOB_SUBMISSION: ""   
              with_items: "{{ jobs_id_fact.split(',') }}"
              when: jobs_id_fact | default('', true) | trim != ''
                            
          when: jobs_del == "tak"
                  
      when: printer_model == 'Xerox WorkCentre 3345'

    - name: Configure Samsung SL-M3870FW printer
      block:
        - name: Print model
          debug:
            msg: "Rozpoznalem drukarke Samsung SL-M3870FW"

        - name: Add email address
          block:
            - name: Get speed no 
              uri:
                url: "http://{{inventory_hostname}}/sws/app/addressbook/GetUsedSpeedNoInABook.jsp"
                method: POST
                return_content: yes
                body_format: form-urlencoded
                body:
                  type: "0"
              register: output_get_speed_no
        
            - name: Parse output
              set_fact:
                output_get_speed_no_fact: "{{ output_get_speed_no.content | from_yaml }}"
            
            - name: Print result
              debug:
                msg: "{{ output_get_speed_no_fact.usedSpeedNo | regex_replace('.*,([0-9]{1,3})', '\\1') | int + 1 }}"
         
            - name: Run URL command 
              uri:
                url: "http://{{inventory_hostname}}/sws/app/addressbook/SetIndividualInABook.jsp"
                method: POST
                return_content: yes
                body_format: form-urlencoded
                body:
                  cmd: add
                  ispeedNo: "{{ output_get_speed_no_fact.usedSpeedNo | regex_replace('.*,([0-9]{1,3})', '\\1') | int + 1 }}"
                  iname: "{{ email }}"
                  email: "{{ email }}"
                  favorite:	"0"
              register: output_set_email
            
            - name: Parse output
              set_fact:
                output_set_email_fact: "{{ output_set_email.content | replace(':', ': ') | from_yaml }}"
        
            - name: Print result
              debug:
                msg: "Ustawiono adres email {{ email }}"
              when: output_set_email_fact.success
              
            - name: Print result
              debug:
                msg: "Nie ustawiono adresu email!!!"
              when: not output_set_email_fact.success
              
          when: email | default('', true) | trim != ''
          
        - name: Delete jobs
          block:
            - name: Run URL command - get jobs id
              uri:
                url: "http://{{inventory_hostname}}/sws/app/gnb/jobs/GetActiveJobs.jsp"
                method: POST
                return_content: yes
                body_format: form-urlencoded
                body:
                  start: "0"
                  limit: "10"
              register: output_del_jobs
              
            - name: Set fact jobs id
              set_fact:
                jobs_id_fact: "{{output_del_jobs.content | replace('\r', ' ') | replace('\n', ' ') | from_yaml }}"
            
            - name: Usuwam zadania!
              debug:
                msg: "{{ jobs_id_fact }}"
                            
          when: jobs_del == "tak"         
      when: printer_model == 'Samsung SL-M3870FW'      
