- name: Check if SNMPv2 is working on remote host
  hosts: "{{ branch_no }}-printer{{printer_no}}"
  connection: local
  gather_facts: no
 
  tasks:
    - name: Get SNMPv2 printer model
      local_action: command snmpget -v2c -c public {{ inventory_hostname }} SNMPv2-MIB::sysDescr.0
      register: response

    - name: Set printer model fact
      set_fact:
        printer_model: "{{ response.stdout | regex_replace('.*STRING: (.*); .*', '\\1') | regex_replace('.*STRING: (.*)', '\\1')}}"

    - name: Configure printer Xerox
      block:
        - name: Print model
          debug:
            msg: "To jest drukarka Xerox"
      when: printer_model == 'Xerox WorkCentre 3345'

    - name: Configure printer Samsung
      block:
        - name: Print model
          debug:
            msg: "To jest drukarka Samsung"
      when: printer_model == 'Samsung SL-M3870FW'      
